# Generated by Django 5.2.7 on 2025-11-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shipping_address',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
