# Generated by Django 5.2.7 on 2025-11-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='store_banner',
            field=models.ImageField(blank=True, null=True, upload_to='vendor/banners/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='store_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor/logos/'),
        ),
    ]
