# Generated by Django 5.2.7 on 2025-11-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_store_banner_customuser_store_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
