# Generated by Django 5.2.7 on 2025-11-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='store_banner',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='store_description',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='store_logo',
        ),
    ]
