# Generated by Django 5.2.7 on 2025-11-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='store_banner',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_banners/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='store_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_logos/'),
        ),
    ]
