# Generated by Django 5.2.8 on 2025-11-12 12:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_store_banner_customuser_store_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='available_for_payout',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
