# Generated by Django 5.2.8 on 2025-11-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_available_for_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='razorpay_account_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
