# Generated by Django 5.2.8 on 2025-11-14 05:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lifetime_net_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
