# Generated by Django 5.2.8 on 2025-11-18 08:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_lifetime_net_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total gross sales for this vendor (before commission)', max_digits=12),
        ),
    ]
