# Generated by Django 5.2.8 on 2025-12-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_total_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='business_reg_id',
            field=models.CharField(blank=True, help_text='Tax ID, GSTIN, etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_document',
            field=models.FileField(blank=True, help_text='Upload Business Proof', null=True, upload_to='vendor_kyc/'),
        ),
    ]
