# Generated by Django 5.2.8 on 2025-12-18 09:20

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_kyc_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kyc_document',
            field=models.FileField(blank=True, help_text='Upload Business Proof', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='vendor_kyc/'),
        ),
    ]
