# Generated by Django 5.2.8 on 2025-12-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_customuser_kyc_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vendor_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
