# Generated by Django 5.2.8 on 2025-11-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_product_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='cloudinary_url',
        ),
        migrations.AddField(
            model_name='category',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
