# Generated by Django 5.2.8 on 2025-11-22 11:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_rename_image_url_product_cloudinary_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cloudinary_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cloudinary_url',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
