# Generated by Django 5.2.8 on 2025-11-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_remove_category_cloudinary_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this category'),
        ),
    ]
