# Generated by Django 5.2.8 on 2025-11-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
